# ruff: noqa: E501
"""BlockId / TransitionId enums.

Generated by `python scripts/gen_block_ids.py` — do not edit by hand.
Add a new block file under `framecraft/blocks/` then re-run the script.
"""

from __future__ import annotations

from enum import StrEnum



class BlockId(StrEnum):
    END_CARD = "end-card"
    GRADIENT_BG = "gradient-bg"
    GRAIN_OVERLAY = "grain-overlay"
    LOWER_THIRD = "lower-third"
    TITLE_CARD = "title-card"


class TransitionId(StrEnum):
    # Populated in M2 when shader transitions are added under
    # framecraft/blocks/transitions/.
    PLACEHOLDER = "placeholder"
