"""Regenerate `src/framecraft/_block_ids.py` from the filesystem.

Convention: one file per block under `src/framecraft/blocks/<module_name>.py`,
where `<module_name>` (e.g. `title_card`) becomes enum entry
`BlockId.TITLE_CARD = "title-card"`.

Modules starting with `_` are skipped. The `transitions/` subpackage
populates `TransitionId` (unused in M1; lands in M2).

Usage:
    python scripts/gen_block_ids.py         # regenerate
    python scripts/gen_block_ids.py --check # exit 1 if regeneration would change anything
"""

from __future__ import annotations

import argparse
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
BLOCKS_DIR = ROOT / "src" / "framecraft" / "blocks"
TRANSITIONS_DIR = BLOCKS_DIR / "transitions"
TARGET = ROOT / "src" / "framecraft" / "_block_ids.py"


def _module_to_entries(directory: pathlib.Path) -> list[tuple[str, str]]:
    """Return sorted (ENUM_NAME, enum-value) pairs for .py files in directory."""
    if not directory.exists():
        return []
    entries: list[tuple[str, str]] = []
    for path in sorted(directory.glob("*.py")):
        name = path.stem
        if name.startswith("_"):
            continue
        if name == "__init__":
            continue
        enum_name = name.upper()
        enum_value = name.replace("_", "-")
        entries.append((enum_name, enum_value))
    return entries


HEADER = '''# ruff: noqa: E501
"""BlockId / TransitionId enums.

Generated by `python scripts/gen_block_ids.py` — do not edit by hand.
Add a new block file under `framecraft/blocks/` then re-run the script.
"""

from __future__ import annotations

from enum import StrEnum
'''


def _render(
    block_entries: list[tuple[str, str]],
    transition_entries: list[tuple[str, str]],
) -> str:
    lines: list[str] = [HEADER, "", ""]
    lines.append("class BlockId(StrEnum):")
    if not block_entries:
        lines.append('    PLACEHOLDER = "placeholder"')
    else:
        for name, value in block_entries:
            lines.append(f'    {name} = "{value}"')
    lines.append("")
    lines.append("")
    lines.append("class TransitionId(StrEnum):")
    if not transition_entries:
        lines.append("    # Populated in M2 when shader transitions are added under")
        lines.append("    # framecraft/blocks/transitions/.")
        lines.append('    PLACEHOLDER = "placeholder"')
    else:
        for name, value in transition_entries:
            lines.append(f'    {name} = "{value}"')
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="exit 1 if output would change")
    args = parser.parse_args()

    rendered = _render(
        _module_to_entries(BLOCKS_DIR),
        _module_to_entries(TRANSITIONS_DIR),
    )

    if args.check:
        current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
        if current != rendered:
            sys.stderr.write(
                f"{TARGET} is stale. Run: python scripts/gen_block_ids.py\n"
            )
            return 1
        return 0

    TARGET.write_text(rendered, encoding="utf-8")
    print(f"wrote {TARGET}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
